export enum ActionTypes {
  GET_COFFEE_TYPES_REQUEST = 'GET_COFFEE_TYPES_REQUEST',
  GET_COFFEE_TYPES_SUCCESS = 'GET_COFFEE_TYPES_SUCCESS',
  GET_COFFEE_TYPES_FAILURE = 'GET_COFFEE_TYPES_FAILURE',
  SET_NEW_ORDER = 'SET_NEW_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
  SET_ORDER_SERVING = 'SET_ORDER_SERVING',
  SET_ORDER_OPTIONS = 'SET_ORDER_OPTIONS',
  SET_ORDER_ADDITIONALS = 'SET_ORDER_ADDITIONALS',
  SET_ORDER_TOTAL_PRICE = 'SET_ORDER_TOTAL_PRICE'
}
